### ISSUE TITLE
Tasks ignore tags and #

### ISSUE THREAD

**Issue by pralayb007** [macedotavares/obsidian-utilities#6] opened 2021-01-14 20:20 UTC
Adding a task with tags (or anything appended by a `#`) ignores the `#` and gets added with just the words. 

Steps to reproduce:
1. Hit the "t" shortcut of the workflow and add "Hello World #test". 
2. Shows up as "Hello World test" on the task file.

**Comment by macedotavares** [comment] 2021-01-15 09:14
I couldn't reproduce this. The `Tasks.md` file was appended with `- [ ] [[2021-01-15]] Hello World #test ^c84c20`.
The entry in the daily note, however, is filtered: `#task [[Tasks#^c84c20|Hello World test]]`. This is intended behaviour, so that no non alphanumeric characters break the link.

Maybe we could have a more permissive filtering, but if the above is what happens in your case as well, I'm closing this issue and creating a new request for the filter part.

**Closed** 2021-01-28 19:24 UTC
